package io.nekohasekai.sagernet.fmt.wireguard

import com.google.gson.JsonArray
import com.google.gson.JsonObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import java.util.Base64
import java.util.zip.Deflater

class AmneziaWireGuardImporterTest {

    @Test
    fun parsesAwg2ConfWithEmptyJunkFieldsAndMultiplePeers() {
        val profiles = AmneziaWireGuardImporter.parseWireGuard(
            """
                ﻿# generated by Amnezia
                [Interface]
                Address = 10.8.1.8/32, fd00::8/128
                PrivateKey = $PRIVATE_KEY
                Jc = 6
                Jmin = 10
                Jmax = 50
                S1 = 89
                S2 = 112
                S3 = 52
                S4 = 19
                H1 = 100-200
                H2 = 201-300
                H3 = 301-400
                H4 = 401-500
                I1 = <r 2><b 0x0102>
                I2 =
                I3 =
                I4 =
                I5 =

                [Peer]
                PublicKey = $PUBLIC_KEY
                PresharedKey = $PRESHARED_KEY
                Endpoint = vpn.example.com:51820

                [Peer]
                PublicKey = $PUBLIC_KEY
                PreSharedKey = $PRESHARED_KEY
                Endpoint = [2001:db8::1]:51821 ; IPv6 peer
            """.trimIndent().replace("\n", "\r\n"),
        )

        assertEquals(2, profiles.size)
        assertEquals("10.8.1.8/32\nfd00::8/128", profiles[0].localAddress)
        assertEquals("vpn.example.com", profiles[0].serverAddress)
        assertEquals(51820, profiles[0].serverPort)
        assertEquals("2001:db8::1", profiles[1].serverAddress)
        assertEquals(51821, profiles[1].serverPort)
        assertEquals(PRESHARED_KEY, profiles[1].peerPreSharedKey)
        assertEquals(1280, profiles[0].mtu)
        assertEquals("<r 2><b 0x0102>", profiles[0].i1)
        assertEquals("", profiles[0].i2)
    }

    @Test
    fun regularWireGuardKeepsExistingDefaultMtu() {
        val profile = AmneziaWireGuardImporter.parseWireGuard(regularWireGuardConf()).single()
        assertEquals(1420, profile.mtu)
        assertEquals("192.0.2.10", profile.serverAddress)
    }

    @Test
    fun explicitMtuWinsForAwg() {
        val profile = AmneziaWireGuardImporter.parseWireGuard(
            awgConf().replace("Jc = 6", "MTU = 1360\nJc = 6"),
        ).single()
        assertEquals(1360, profile.mtu)
    }

    @Test
    fun normalizesBareLocalAddressesFromConfAndVpn() {
        val bareAddressConf = awgConf().replace(
            "Address = 10.8.1.8/32",
            "Address = 172.16.0.2, fd00::2",
        )

        val confProfile = AmneziaWireGuardImporter.parseWireGuard(bareAddressConf).single()
        val vpnProfile = AmneziaWireGuardImporter.parseVpn(
            encodeVpn(rootWithContainers(awgContainer(bareAddressConf)), compressed = true),
        ).single()

        assertEquals("172.16.0.2/32\nfd00::2/128", confProfile.localAddress)
        assertEquals(confProfile.localAddress, vpnProfile.localAddress)
    }

    @Test
    fun decodesQtCompressedVpnAndUsesJsonMtu() {
        val vpn = encodeVpn(rootWithContainers(awgContainer(awgConf(), mtu = 1300)), compressed = true)
        val profile = AmneziaWireGuardImporter.parseVpn(vpn).single()

        assertEquals("Synthetic server", profile.name)
        assertEquals(1300, profile.mtu)
        assertEquals(6, profile.jc)
    }

    @Test
    fun decodesUncompressedVpnJson() {
        val vpn = encodeVpn(rootWithContainers(awgContainer(awgConf())), compressed = false)
        assertEquals(1, AmneziaWireGuardImporter.parseVpn(vpn).size)
    }

    @Test
    fun decodesQrPayloadWithoutVpnScheme() {
        val vpn = encodeVpn(rootWithContainers(awgContainer(awgConf())), compressed = true)
        val payload = vpn.removePrefix("vpn://")

        val profile = AmneziaWireGuardImporter.tryParseUnprefixedVpn(payload)?.single()

        assertEquals("Synthetic server", profile?.name)
        assertEquals("192.0.2.10", profile?.serverAddress)
    }

    @Test
    fun leavesGenericBase64ForExistingImporters() {
        val genericSubscription = Base64.getUrlEncoder().withoutPadding()
            .encodeToString("ss://example\nvmess://example".toByteArray())

        assertEquals(null, AmneziaWireGuardImporter.tryParseUnprefixedVpn(genericSubscription))
    }

    @Test
    fun mixedVpnImportsOnlyAwgContainersAndSuffixesNames() {
        val unsupported = JsonObject().apply {
            addProperty("container", "amnezia-xray")
            add("xray", JsonObject())
        }
        val root = rootWithContainers(
            unsupported,
            awgContainer(awgConf()).apply { addProperty("container", "amnezia-awg") },
            awgContainer(awgConf().replace("192.0.2.10", "192.0.2.11")),
        )

        val profiles = AmneziaWireGuardImporter.parseVpn(encodeVpn(root, compressed = true))

        assertEquals(2, profiles.size)
        assertEquals("Synthetic server", profiles[0].name)
        assertEquals("Synthetic server (2)", profiles[1].name)
        assertEquals("192.0.2.11", profiles[1].serverAddress)
    }

    @Test
    fun skipsBrokenAwgContainerWhenAnotherIsValid() {
        val broken = JsonObject().apply {
            addProperty("container", "amnezia-awg2")
            add("awg", JsonObject())
        }
        val root = rootWithContainers(broken, awgContainer(awgConf()))

        val profiles = AmneziaWireGuardImporter.parseVpn(encodeVpn(root, compressed = true))

        assertEquals(1, profiles.size)
        assertEquals("Synthetic server", profiles.single().name)
    }

    @Test
    fun rejectsInvalidBase64WrongLengthAndOversizedPayload() {
        assertReason(AmneziaWireGuardImporter.ErrorReason.INVALID_CONTAINER, "vpn://not!base64")

        val json = rootWithContainers(awgContainer(awgConf())).toString().toByteArray()
        val wrongLength = qtCompressed(json).also { bytes ->
            ByteBuffer.wrap(bytes).putInt(1)
        }
        assertReason(
            AmneziaWireGuardImporter.ErrorReason.INVALID_CONTAINER,
            "vpn://" + Base64.getUrlEncoder().withoutPadding().encodeToString(wrongLength),
        )

        val oversizedHeader = ByteBuffer.allocate(6).apply {
            putInt(AmneziaWireGuardImporter.MAX_UNCOMPRESSED_SIZE + 1)
            put(0x78.toByte())
            put(0x9c.toByte())
        }.array()
        assertReason(
            AmneziaWireGuardImporter.ErrorReason.INVALID_CONTAINER,
            "vpn://" + Base64.getUrlEncoder().withoutPadding().encodeToString(oversizedHeader),
        )
    }

    @Test
    fun reportsWhenVpnHasNoAwgProfiles() {
        val root = rootWithContainers(JsonObject().apply {
            addProperty("container", "amnezia-xray")
        })
        assertReason(
            AmneziaWireGuardImporter.ErrorReason.NO_AWG_PROFILES,
            encodeVpn(root, compressed = true),
        )
    }

    private fun assertReason(reason: AmneziaWireGuardImporter.ErrorReason, vpn: String) {
        val error = assertThrows(AmneziaWireGuardImporter.ImportException::class.java) {
            AmneziaWireGuardImporter.parseVpn(vpn)
        }
        assertEquals(reason, error.reason)
    }

    private fun rootWithContainers(vararg containers: JsonObject) = JsonObject().apply {
        addProperty("description", "Synthetic server")
        addProperty("hostName", "192.0.2.10")
        add("containers", JsonArray().apply { containers.forEach { add(it) } })
    }

    private fun awgContainer(conf: String, mtu: Int? = null) = JsonObject().apply {
        addProperty("container", "amnezia-awg2")
        add("awg", JsonObject().apply {
            addProperty("last_config", JsonObject().apply {
                addProperty("config", conf)
                mtu?.let { addProperty("mtu", it.toString()) }
            }.toString())
        })
    }

    private fun encodeVpn(root: JsonObject, compressed: Boolean): String {
        val json = root.toString().toByteArray()
        val bytes = if (compressed) qtCompressed(json) else json
        return "vpn://" + Base64.getUrlEncoder().withoutPadding().encodeToString(bytes)
    }

    private fun qtCompressed(input: ByteArray): ByteArray {
        val deflater = Deflater().apply {
            setInput(input)
            finish()
        }
        val compressed = ByteArrayOutputStream().use { output ->
            val buffer = ByteArray(1024)
            while (!deflater.finished()) {
                val count = deflater.deflate(buffer)
                output.write(buffer, 0, count)
            }
            output.toByteArray()
        }
        deflater.end()
        return ByteBuffer.allocate(4 + compressed.size)
            .putInt(input.size)
            .put(compressed)
            .array()
    }

    private fun regularWireGuardConf() = """
        [Interface]
        Address = 10.0.0.2/32
        PrivateKey = $PRIVATE_KEY

        [Peer]
        PublicKey = $PUBLIC_KEY
        Endpoint = 192.0.2.10:51820
    """.trimIndent()

    private fun awgConf() = """
        [Interface]
        Address = 10.8.1.8/32
        PrivateKey = $PRIVATE_KEY
        Jc = 6
        Jmin = 10
        Jmax = 50
        S1 = 89
        S2 = 112
        S3 = 52
        S4 = 19
        H1 = 100-200
        H2 = 201-300
        H3 = 301-400
        H4 = 401-500
        I1 = <r 2><b 0x0102>
        I2 =
        I3 =
        I4 =
        I5 =

        [Peer]
        PublicKey = $PUBLIC_KEY
        PresharedKey = $PRESHARED_KEY
        Endpoint = 192.0.2.10:51820
    """.trimIndent()

    companion object {
        private const val PRIVATE_KEY = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
        private const val PUBLIC_KEY = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB="
        private const val PRESHARED_KEY = "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC="
    }
}
