#!/bin/bash

source ./env_java.sh || true
source ../buildScript/init/env_ndk.sh

BUILD=".build"

rm -rf $BUILD/android \
  $BUILD/java \
  $BUILD/javac-output \
  $BUILD/src

if [ -z "$GOPATH" ]; then
  GOPATH=$(go env GOPATH)
fi

export GOBIND=gobind-matsuri

# Inject the real sing-box version so the About screen shows it instead of "unknown".
# gomobile bind does not reliably forward `-ldflags -X` to the gobind-generated package
# (upstream NekoBox forks have long shown "unknown"), so instead generate a tiny Go file
# compiled into libcore that sets constant.Version at init time. Deterministic and not
# dependent on linker flag forwarding.
# get_source.sh clones sing-box to the parent of the repo root; build.sh runs from
# libcore/, so the clone is two levels up (../../sing-box). Probe a few candidates.
SING_BOX_DIR=""
for cand in ../../sing-box ../sing-box ../../../sing-box; do
  if [ -d "$cand" ] && [ -e "$cand/go.mod" ]; then
    SING_BOX_DIR="$cand"
    break
  fi
done
LIBNEKO_DIR=""
for cand in ../../libneko ../libneko ../../../libneko; do
  if [ -d "$cand" ] && [ -e "$cand/go.mod" ]; then
    LIBNEKO_DIR="$cand"
    break
  fi
done
SING_BOX_VERSION=""
# Preferred source: explicit pin in get_source_env.sh (deterministic, no tag dependency).
if [ -f ../buildScript/lib/core/get_source_env.sh ]; then
  # shellcheck disable=SC1091
  source ../buildScript/lib/core/get_source_env.sh 2>/dev/null || true
  SING_BOX_VERSION="${VERSION_SING_BOX:-}"
fi

# Local sibling replacements must match the source commits used by CI. This prevents an AAR
# from silently depending on whichever revisions happen to be checked out beside this repo.
# Deliberate experiments can opt out with ALLOW_UNPINNED_SIBLINGS=1.
check_sibling_pin() {
  local dir="$1"
  local expected="$2"
  local label="$3"
  [ -z "$dir" ] && return
  local actual
  actual="$(git -C "$dir" rev-parse HEAD 2>/dev/null)" || actual=unknown
  if [ -z "$expected" ] || [ "$actual" != "$expected" ]; then
    echo "ERROR: $label checkout is at $actual but CI pins $expected" >&2
    echo "       checkout the pinned revision or set ALLOW_UNPINNED_SIBLINGS=1." >&2
    exit 1
  fi
}
if [ "${ALLOW_UNPINNED_SIBLINGS:-0}" != "1" ]; then
  check_sibling_pin "$SING_BOX_DIR" "${COMMIT_SING_BOX:-}" "sing-box"
  check_sibling_pin "$LIBNEKO_DIR" "${COMMIT_LIBNEKO:-}" "libneko"
fi

# Fallbacks if the pin is missing: read_tag, then git describe.
if [ -z "$SING_BOX_VERSION" ] && [ -n "$SING_BOX_DIR" ]; then
  git -C "$SING_BOX_DIR" fetch --tags --force origin 2>/dev/null || true
  SING_BOX_VERSION="$(cd "$SING_BOX_DIR" && CGO_ENABLED=0 go run ./cmd/internal/read_tag 2>/dev/null || true)"
  if [ -z "$SING_BOX_VERSION" ] || [ "$SING_BOX_VERSION" = "unknown" ]; then
    SING_BOX_VERSION="$(git -C "$SING_BOX_DIR" describe --tags --always 2>/dev/null || true)"
  fi
fi
# Remove any stale generated file so a failed lookup falls back to constant's default
# ("unknown") rather than a previous run's value.
rm -f version_gen.go
if [ -z "$SING_BOX_VERSION" ] || [ "$SING_BOX_VERSION" = "unknown" ]; then
  echo ">> WARNING: could not determine sing-box version (dir='$SING_BOX_DIR'); About will show 'unknown'"
else
  echo ">> sing-box version: $SING_BOX_VERSION (from '$SING_BOX_DIR')"
  # Sanitize to a safe Go string literal (alnum, dot, dash, plus only).
  SAFE_VERSION="$(printf '%s' "$SING_BOX_VERSION" | tr -cd 'A-Za-z0-9.+-')"
  cat > version_gen.go <<EOF
// Code generated by build.sh. DO NOT EDIT.
package libcore

import "github.com/sagernet/sing-box/constant"

func init() {
	if constant.Version == "" || constant.Version == "unknown" {
		constant.Version = "${SAFE_VERSION}"
	}
}
EOF
fi

# 16 KB page alignment (issue #1125): Android 15+ may use 16 KB memory pages, which
# requires native .so LOAD segments aligned to 16384. Force the external linker to use a
# 16 KB max/common page size so libgojni.so is aligned regardless of the gomobile/Go default.
"$GOPATH"/bin/gomobile-matsuri bind -v -androidapi 21 -cache "$(realpath $BUILD)" -trimpath -ldflags='-s -w -extldflags=-Wl,-z,max-page-size=16384,-z,common-page-size=16384' -tags='with_conntrack,with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api' . || exit 1
rm -r libcore-sources.jar

proj=../app/libs
mkdir -p $proj
cp -f libcore.aar $proj
echo ">> install $(realpath $proj)/libcore.aar"
